language: node_js
node_js:
 - 6

before_install:
 - npm install yarn -g

install:
 - yarn install

before_deploy:
 - yarn run compile
 - yarn run build

deploy:
 provider: npm
 email: "lalalic@139.com"
 api_key: $NPM_KEY
 on:
  branch: master
  tags: true
