language: node_js
node_js:
 - 6

before_install:
 - npm install yarn -g

install:
 - yarn install
 - yarn run compile
 - yarn run build
 - yarn info docx4js --json > info.json
 - export LATEST=$(node -p "require('./info.json').data['dist-tags'].latest")
 - export CURRENT=$(node -p "require('./package.json').version")


deploy:
 provider: npm
 email: "lalalic@139.com"
 api_key: $NPM_KEY
 skip_cleanup: true 
 on:
  branch: master
  condition: "$LATEST != $CURRENT"
